### PR TITLE
[Cleanup] - Final Report

### LINKED ISSUE #121: [CSCE431 Feature] - Final Report
### Description

As a professor, I want a final report

### PR DESCRIPTION
**Pull request by rebeccamcfadden**
### Pivotal Tracker
- N/A

### Description / PR Commit Message

Created report

Waiting to merge until approved by Ritchey on Friday

### Guidance for Review

?

### Author's Checklist
- [X] Created PDF of Report
[paper](https://github.com/gatekeeper-tamu/gatekeeper/blob/ed50eb48a99454b5a560818e81c6fbcf6946a9b5/docs/Spring2022/FINAL_REPORT.pdf)

### CODE REVIEW

**Comment by rebeccamcfadden** [comment]
waiting to merge until demo videos are posted

**Review by coraenglish — APPROVED** [review]
Looks good, for some reason the new changes I made aren't showing up on our main or test deployment which would change the groups screenshot (and technically all of the others since the navbar logo changed but that's very minor). Already gave you my entire review. I can also add the video link in if you want to wash your hands of this haha.

**Comment by rebeccamcfadden** [comment]
> Looks good, for some reason the new changes I made aren't showing up on our main or test deployment which would change the groups screenshot (and technically all of the others since the navbar logo changed but that's very minor). Already gave you my entire review. I can also add the video link in if you want to wash your hands of this haha.

Updated the pdf with new images and link

**Comment by rebeccamcfadden** [comment]
still waiting on demo video

**Pull request merged**
